[[language]]
name = "c"
language-id = "c"
formatter = {command = "clang-format", args = ["%{buffer_name}"]}

[[language]]
name = "cpp"
language-id = "cpp"
formatter = {command = "clang-format", args = ["%{buffer_name}"]}

[language-server.clangd]
command = "clangd"
args = ["--background-index", "--clang-tidy", "--function-arg-placeholders=1", "--header-insertion=never", "--pch-storage=memory", "--log=error"]
