set -g status-position top            # 顶部显示状态栏
set -g status-left ''                 # 左状态栏内容
set -g status-left-length 0           # 左状态栏宽度
set -g status-right ''                # 右状态栏内容
set -g status-right-length 0          # 右状态栏宽度
set -g status-justify absolute-centre # 窗口列表居中显示
set -g automatic-rename off           # 关闭自动重命名窗口

set -g status-style                "bg=#6e8b3d,fg=gray40"
set -g window-status-style         "bg=#a2cd5a,fg=gray40"
set -g window-status-last-style    "bg=#bcee68,fg=gray40,bold"
set -g window-status-current-style "bg=#caff70,fg=black,bright,underscore"
set -g window-status-separator ' '

set -g mode-keys vi                   # 拷贝模式下使用 vi 模式
set -g set-clipboard on               # 开启 tmux 与系统剪贴板的交互功能
set -g status-keys vi                 # 状态栏下使用 vi 模式
set -g mouse on                       # 支持鼠标事件

